### PR TITLE
Bump to 0.5.0 versions

### PR DESCRIPTION
**Pull request by joshmoore**
See https://github.com/ome/ome-cmake-superbuild/pull/173

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Ready to merge. Do we want to try and apply the tag strategy used for the omero-web,server Docker images for this repository?

**Comment by joshmoore** [comment]
i.e. this will become latest and then we manually push the tag?

**Comment by sbesson** [comment]
Yes, that would be my proposal as this would also not interfere with the `vx.y.z` tag esp. if we are migrating these Docker files to ome-files-cpp (https://github.com/openmicroscopy/ome-files-cpp-u1604-docker/issues/12)

**Comment by rleigh-codelibre** [comment]
The numbers are correct and it builds without error, so looks good to merge.

**Pull request merged**
