### PR TITLE
Update the Dockerfile to build the master OME Files branch

### PR DESCRIPTION
**Pull request by sbesson**
- Clone the latest releases of ome-common-cpp, ome-model and ome-qtwidgets
- Clone the master branch of `ome-files-cpp`
- Remove DCMAKE_CXX_STANDARD

To test this PR, retrieve the latest Docker image from https://hub.docker.com/r/snoopycrimecop/ome-files-cpp-u1604 and check it runs as expected (`ome-files info`)

### CODE REVIEW

**Comment by sbesson** [comment]
https://hub.docker.com/r/snoopycrimecop/ome-files-cpp-u1604/builds/bodmctuj5zcjb2ssmswmehg/ shows that the current `master` branch also needs to be patched for the uncapped Sphinx version - opened as https://github.com/ome/ome-files-cpp/pull/69

**Comment by simleo** [comment]
Why is `-DCMAKE_CXX_STANDARD=11` not needed anymore? Ubuntu 16.04 still provides Boost 1.58.

**Comment by sbesson** [comment]
@simleo see https://github.com/ome/ome-files-cpp/pull/68 and the PR discussion for the rationale about the change. Removing the option was sufficient for me to reproduce the Ubuntu 16.04 issue raised and fixed by the PR. We can certainly decide whether our Ubuntu 16.04 Docker image should build strictly with C++11 or with later standards if available.

**Comment by dgault** [comment]
Using master_merge_daily I was able to retrieve and run the image without any problems. Running the command ome-files info completed as expected with the correct metadata shown. Running the --version command also appears to be correct.

This looks to be working as expected.

**Comment by sbesson** [comment]
Discussed the flag with @simleo, merging this PR as it is so that we can consume the development branch for the benchmarking work. One note is that https://github.com/ome/ome-cmake-superbuild/pull/105 should probably be updated as this is now fixed in the code itself.

**Pull request merged**
